package com.talentflow.config;

import com.talentflow.entity.User;
import com.talentflow.repository.UserRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.CommandLineRunner;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Component;
import java.time.LocalDateTime;

/**
 * Data Initializer - Creates demo accounts on startup
 */
@Slf4j
@Component
@RequiredArgsConstructor
public class DataInitializer implements CommandLineRunner {

    private final UserRepository userRepository;
    private final PasswordEncoder passwordEncoder;

    @Override
    public void run(String... args) throws Exception {
        log.info("🚀 Initializing demo accounts...");
        
        try {
            // Create demo student account
            createDemoStudentAccount();
            
            // Create demo recruiter account
            createDemoRecruiterAccount();
            
            log.info("✅ Demo accounts initialized");
        } catch (Exception e) {
            log.warn("⚠️  Could not initialize demo accounts. Database may not be available yet. Error: {}", e.getMessage());
            log.info("Demo accounts can be created manually via signup endpoint.");
        }
    }

    private void createDemoStudentAccount() {
        String email = "student@example.com";
        
        if (userRepository.findByEmail(email).isPresent()) {
            log.info("📚 Student account already exists: {}", email);
            return;
        }
        
        User student = new User(
                null, // id (auto-generated by MongoDB)
                "John Student",
                email,
                passwordEncoder.encode("Test@123"),
                "9876543210",
                "STUDENT",
                null, // skills
                null, // education
                null, // experience
                null, // resumeId
                null, // profilePhoto
                0.0,  // profileCompletion
                null, // companyName
                null, // companyWebsite
                null, // companyDescription
                null, // companyLocation
                true, // isActive
                LocalDateTime.now(), // createdAt
                LocalDateTime.now()  // updatedAt
        );
        
        userRepository.save(student);
        log.info("✅ Created demo student account: {} (Password: Test@123)", email);
    }

    private void createDemoRecruiterAccount() {
        String email = "recruiter@example.com";
        
        if (userRepository.findByEmail(email).isPresent()) {
            log.info("🏢 Recruiter account already exists: {}", email);
            return;
        }
        
        User recruiter = new User(
                null, // id (auto-generated by MongoDB)
                "Jane Recruiter",
                email,
                passwordEncoder.encode("Test@123"),
                "9876543211",
                "RECRUITER",
                null, // skills
                null, // education
                null, // experience
                null, // resumeId
                null, // profilePhoto
                0.0,  // profileCompletion
                null, // companyName
                null, // companyWebsite
                null, // companyDescription
                null, // companyLocation
                true, // isActive
                LocalDateTime.now(), // createdAt
                LocalDateTime.now()  // updatedAt
        );
        
        userRepository.save(recruiter);
        log.info("✅ Created demo recruiter account: {} (Password: Test@123)", email);
    }
}
