package com.talentflow.config;

import com.talentflow.entity.Job;
import com.talentflow.entity.User;
import com.talentflow.repository.JobRepository;
import com.talentflow.repository.UserRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.CommandLineRunner;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Component;
import java.time.LocalDateTime;
import java.util.Arrays;

/**
 * Data Initializer - Creates demo accounts and jobs on startup
 */
@Slf4j
@Component
@RequiredArgsConstructor
public class DataInitializer implements CommandLineRunner {

    private final UserRepository userRepository;
    private final JobRepository jobRepository;
    private final PasswordEncoder passwordEncoder;

    @Override
    public void run(String... args) throws Exception {
        log.info("🚀 Initializing demo data...");
        
        try {
            // Create demo student account
            String studentId = createDemoStudentAccount();
            
            // Create demo recruiter account
            String recruiterId = createDemoRecruiterAccount();
            
            // Create demo jobs
            createDemoJobs(recruiterId);
            
            log.info("✅ Demo data initialized");
        } catch (Exception e) {
            log.warn("⚠️  Could not initialize demo data. Database may not be available yet. Error: {}", e.getMessage());
            log.info("Demo accounts can be created manually via signup endpoint.");
        }
    }

    private String createDemoStudentAccount() {
        String email = "student@example.com";
        
        // Delete existing account to ensure fresh password
        userRepository.findByEmail(email).ifPresent(userRepository::delete);
        
        User student = new User(
                null, // id (auto-generated by MongoDB)
                "Test Student",
                email,
                passwordEncoder.encode("password"),
                "9876543210",
                "STUDENT",
                null, // skills
                null, // education
                null, // experience
                null, // resumeId
                null, // profilePhoto
                0.0,  // profileCompletion
                null, // companyName
                null, // companyWebsite
                null, // companyDescription
                null, // companyLocation
                true, // isActive
                LocalDateTime.now(), // createdAt
                LocalDateTime.now()  // updatedAt
        );
        
        User saved = userRepository.save(student);
        log.info("✅ Created demo student account: {} (Password: password)", email);
        return saved.getId();
    }

    private String createDemoRecruiterAccount() {
        String email = "recruiter@example.com";
        
        // Delete existing account to ensure fresh password
        userRepository.findByEmail(email).ifPresent(userRepository::delete);
        
        User recruiter = new User(
                null, // id (auto-generated by MongoDB)
                "Jane Recruiter",
                email,
                passwordEncoder.encode("password"),
                "9876543211",
                "RECRUITER",
                null, // skills
                null, // education
                null, // experience
                null, // resumeId
                null, // profilePhoto
                0.0,  // profileCompletion
                "TechCorp Inc",
                "https://techcorp.example.com",
                "Leading technology company",
                "New York, NY",
                true, // isActive
                LocalDateTime.now(), // createdAt
                LocalDateTime.now()  // updatedAt
        );
        
        User saved = userRepository.save(recruiter);
        log.info("✅ Created demo recruiter account: {} (Password: password)", email);
        return saved.getId();
    }

    private void createDemoJobs(String recruiterId) {
        // Clear old jobs and create fresh ones
        jobRepository.deleteAll();
        log.info("Cleared existing jobs, creating fresh demo jobs...");

        Job job1 = new Job();
        job1.setRecruiterId(recruiterId);
        job1.setTitle("Senior Full Stack Developer");
        job1.setCompanyName("TechCorp Inc");
        job1.setCompanyDescription("Leading technology company specializing in cloud solutions");
        job1.setCompanyWebsite("https://techcorp.example.com");
        job1.setLocation("New York, NY");
        job1.setDescription("We are looking for an experienced Full Stack Developer to join our team. You will be responsible for building and maintaining scalable web applications using modern technologies. Required skills include React, Node.js, MongoDB, and cloud deployment experience.");
        job1.setSalary(150000L);
        job1.setJobType("Full Time");
        job1.setExperienceRequired(5);
        job1.setRequiredSkills(Arrays.asList("React", "Node.js", "MongoDB", "Docker", "AWS"));
        job1.setRequirements(Arrays.asList(
            "5+ years of software development experience",
            "Expert knowledge of React and Node.js",
            "Experience with MongoDB and relational databases",
            "Strong understanding of REST APIs and microservices",
            "Excellent problem-solving skills"
        ));
        job1.setApplicantCount(0);
        job1.setShortlistedCount(0);
        job1.setIsClosed(false);
        job1.setCreatedAt(LocalDateTime.now());
        job1.setUpdatedAt(LocalDateTime.now());
        jobRepository.save(job1);

        Job job2 = new Job();
        job2.setRecruiterId(recruiterId);
        job2.setTitle("Frontend Developer");
        job2.setCompanyName("TechCorp Inc");
        job2.setCompanyDescription("Leading technology company specializing in cloud solutions");
        job2.setCompanyWebsite("https://techcorp.example.com");
        job2.setLocation("San Francisco, CA");
        job2.setDescription("Join our frontend team and create amazing user experiences! We're looking for developers who are passionate about building beautiful, responsive interfaces.");
        job2.setSalary(120000L);
        job2.setJobType("Full Time");
        job2.setExperienceRequired(3);
        job2.setRequiredSkills(Arrays.asList("React", "TypeScript", "CSS", "Tailwind", "Git"));
        job2.setRequirements(Arrays.asList(
            "3+ years of React development",
            "Strong CSS and responsive design skills",
            "Experience with TypeScript",
            "Knowledge of state management tools"
        ));
        job2.setApplicantCount(0);
        job2.setShortlistedCount(0);
        job2.setIsClosed(false);
        job2.setCreatedAt(LocalDateTime.now());
        job2.setUpdatedAt(LocalDateTime.now());
        jobRepository.save(job2);

        Job job3 = new Job();
        job3.setRecruiterId(recruiterId);
        job3.setTitle("Backend Engineer");
        job3.setCompanyName("TechCorp Inc");
        job3.setCompanyDescription("Leading technology company specializing in cloud solutions");
        job3.setCompanyWebsite("https://techcorp.example.com");
        job3.setLocation("Remote");
        job3.setDescription("Design and implement scalable backend systems. Work with microservices, databases, and cloud infrastructure.");
        job3.setSalary(140000L);
        job3.setJobType("Full Time");
        job3.setExperienceRequired(4);
        job3.setRequiredSkills(Arrays.asList("Java", "Spring Boot", "PostgreSQL", "Docker", "Kubernetes"));
        job3.setRequirements(Arrays.asList(
            "4+ years backend development experience",
            "Strong Java and Spring Boot knowledge",
            "Database design and optimization",
            "Cloud deployment experience"
        ));
        job3.setApplicantCount(0);
        job3.setShortlistedCount(0);
        job3.setIsClosed(false);
        job3.setCreatedAt(LocalDateTime.now());
        job3.setUpdatedAt(LocalDateTime.now());
        jobRepository.save(job3);

        log.info("✅ Created 3 demo jobs");
    }
}
